export enum AppBridge {
	WEB_READY = 'WEB_READY',
	TEST_MESSAGE = 'TEST_MESSAGE',
	DEVICE_INFO = 'DEVICE_INFO',

	// 햅틱 피드백 https://github.com/mkuczera/react-native-haptic-feedback
	IMPACT_LIGHT = 'IMPACT_LIGHT',
	IMPACT_MEDIUM = 'IMPACT_MEDIUM',
	IMPACT_HEAVY = 'IMPACT_HEAVY',
	RIGID = 'RIGID',
	SOFT = 'SOFT',
	NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS',
	NOTIFICATION_WARNING = 'NOTIFICATION_WARNING',
	NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
	// only ios
	SELECTION = 'SELECTION',

	// only android
	CLOCK_TICK = 'CLOCK_TICK',
	CONTEXT_CLICK = 'CONTEXT_CLICK',
	KEYBOARD_PRESS = 'KEYBOARD_PRESS',
	KEYBOARD_RELEASE = 'KEYBOARD_RELEASE',
	KEYBOARD_TAP = 'KEYBOARD_TAP',
	LONG_PRESS = 'LONG_PRESS',
	TEXT_HANDLE_MOVE = 'TEXT_HANDLE_MOVE',
	VIRTUAL_KEY = 'VIRTUAL_KEY',
	VIRTUAL_KEY_RELEASE = 'VIRTUAL_KEY_RELEASE',
	EFFECT_CLICK = 'EFFECT_CLICK',
	EFFECT_DOUBLE_CLICK = 'EFFECT_DOUBLE_CLICK',
	EFFECT_HEAVY_CLICK = 'EFFECT_HEAVY_CLICK',
	EFFECT_TICK = 'EFFECT_TICK'
	// 햅틱 끝
}

export interface FromAppMessage {
	type: FromApp
	data?: unknown
}

export enum FromApp {
	APP_READY = 'APP_READY',
	DEVICE_INFO = 'DEVICE_INFO'
}
